<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks>net8.0; net481</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ImplicitUsings>disable</ImplicitUsings>
        <RootNamespace>BenchmarkDotNetSample</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="BenchmarkDotNet" Version="0.15.2" />
    </ItemGroup>

</Project>
