<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <TargetFrameworks>net45;net8.0</TargetFrameworks>

    <OutputPath>build/bin/</OutputPath>
    <BaseIntermediateOutputPath>build/obj/</BaseIntermediateOutputPath>
    <IntermediateOutputPath>$(BaseIntermediateOutputPath)</IntermediateOutputPath>
  </PropertyGroup>
</Project>
